const express = require('express')
const router = express.Router()

const authRoutes = require('./auth.routes')
const userRoutes = require('./user.routes')
const dashboardRoutes = require('./dashboard.routes')
const newsRoutes = require('./news.routes')
const pollRoutes = require('./poll.routes')
const trainingRoutes = require('./training.routes')
const fileRoutes = require('./file.routes')
const conversationRoutes = require('./conversation.routes')
const notificationRoutes = require('./notification.routes')
const adminRoutes = require('./admin.routes')
const leaveRoutes = require('./leave.routes')
const logsRoutes = require('./logs.routes')
const reportsRoutes = require('./reports.routes')
const broadcastRoutes = require('./broadcast.routes')
const taskRoutes = require('./task.routes')
const labelRoutes = require('./label.routes')
const expenseRoutes = require('./expense.routes')
const calendarRoutes = require('./calendar.routes')
const suggestionRoutes = require('./suggestion.routes')
const celebrationRoutes = require('./celebration.routes')
const reactionRoutes = require('./reaction.routes')
const activityRoutes = require('./activity.routes')
const { maintenanceGuard, isMaintenanceMode } = require('../middleware/maintenance.middleware')

// Public bakım durumu — frontend kapısı bunu sorgular (guard'dan muaf)
router.get('/maintenance', (req, res) =>
  res.json({ success: true, data: { maintenance: isMaintenanceMode() } })
)

// Auth guard'dan ÖNCE: bakım modunda da giriş yapılabilmeli (özellikle ADMIN)
router.use('/auth', authRoutes)

// Bu noktadan sonrası bakım modunda yalnızca ADMIN'e açık
router.use(maintenanceGuard)

router.use('/users', userRoutes)
router.use('/dashboard', dashboardRoutes)
router.use('/news', newsRoutes)
router.use('/polls', pollRoutes)
router.use('/training', trainingRoutes)
router.use('/files', fileRoutes)
router.use('/conversations', conversationRoutes)
router.use('/notifications', notificationRoutes)
router.use('/admin', adminRoutes)
router.use('/leaves', leaveRoutes)
router.use('/logs', logsRoutes)
router.use('/reports', reportsRoutes)
router.use('/broadcast', broadcastRoutes)
router.use('/tasks', taskRoutes)
router.use('/labels', labelRoutes)
router.use('/expenses', expenseRoutes)
router.use('/suggestions', suggestionRoutes)
router.use('/celebrations', celebrationRoutes)
router.use('/calendar', calendarRoutes)
router.use('/conversations/:convId/messages/:msgId/reactions', reactionRoutes)
router.use('/activity', activityRoutes)

module.exports = router