export const QUERY_KEYS = {
  AUTH_ME: 'auth-me',
  DASHBOARD_STATS: 'dashboard-stats',
  DASHBOARD_RECENT_NEWS: 'dashboard-recent-news',
  DASHBOARD_ACTIVE_POLLS: 'dashboard-active-polls',
  NEWS: 'news',
  NEWS_DETAIL: 'news-detail',
  POLLS: 'polls',
  POLL_DETAIL: 'poll-detail',
  POLL_RESULTS: 'poll-results',
  TRAINING: 'training',
  TRAINING_DETAIL: 'training-detail',
  TRAINING_CATEGORIES: 'training-categories',
  CONVERSATIONS: 'conversations',
  CONVERSATION_DETAIL: 'conversation-detail',
  MESSAGES: 'messages',
  NOTIFICATIONS: 'notifications',
  UNREAD_COUNT: 'unread-count',
  USERS: 'users',
  USER_DETAIL: 'user-detail',
  ADMIN_STATS: 'admin-stats',
  ADMIN_SETTINGS: 'admin-settings',
}