export const ROUTES = {
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  DASHBOARD: '/',
  NEWS: '/news',
  NEWS_DETAIL: '/news/:id',
  POLLS: '/polls',
  TRAINING: '/training',
  TRAINING_DETAIL: '/training/:id',
  MESSAGES: '/messages',
  NOTIFICATIONS: '/notifications',
  PROFILE: '/profile',
  ADMIN: '/admin',
  ADMIN_USERS: '/admin/users',
  ADMIN_SETTINGS: '/admin/settings',
  NOT_FOUND: '*',
}